### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by jonschlinkert** [handlebars-lang/docs#1]
continuing the discussion from https://github.com/wycats/handlebars.js/issues/1345

@nknapp per your [last comment](https://github.com/wycats/handlebars.js/issues/1345#issuecomment-302517882), how about if we just start adding the project scaffold and build out from there? 

Fwiw, I don't have any hard requirements or expectations, I just like the idea of helping out with this. We benefit from it because we use handlebars a lot, and we get a lot of handlebars questions on our projects. Improving the handlebars docs will help with that (which we're obliged to do). To that end, if there are things you want to get started on, please feel free to do that, then I'll just pull down whatever you do and join along. @doowb and I are easy going and can adapt to whatever work style we need to.

**Comment by nknapp** [comment]
Yes, the scaffold was what you wanted to do. At least that's what I understood. I'm waiting for that first push. Then we can see where we are going.

**Comment by nknapp** [comment]
Oh and: Although I believe I am pretty good at english, I am not a native speaker. This may lead to misunderstandings. Please just keep in mind that I might just not know the right words if I say something odd.

**Comment by jonschlinkert** [comment]
> Please just keep in mind that I might just not know the right words if I say something odd.

ha, no worries. I am a native speaker and I say odd things all the time lol

**Comment by jonschlinkert** [comment]
@nknapp I still don't have push access but we can work around that until it's figured out. Sorry I just found your email about slack in my gmail junk bin. strange that it got sent there. 

I have some stuff to push up for the handlebars, but I've also been trying to use the same templates and structure on other projects of mine, just to test out how easy they are to use and maintain before we commit to anything here.

**Comment by nknapp** [comment]
Hi again. I thought I had written an answer to this, but I can't find it.

I have made you owner of the group again, but with your problem of pushing to the project... I'm not sure what I can do to help you. It works for me and I don't see any difference between us, concerning access rights and roles. It seems to me that the github-support team are the only ones who can help here, but you'd have to talk to them yourself.

**Comment by nknapp** [comment]
I have started scaffolding a site with vuepress. I'll close this issue.
