### ISSUE TITLE
Reference to "New site"

### ISSUE THREAD

**Issue by Tejas-Ladhani** [handlebars-lang/docs#108]
I was going through https://github.com/handlebars-lang/docs/blob/master/src/contributing/index.md#what-can-i-contribute. 
What is the new site's location, or does it need to be created and deployed?

**Comment by ilharp** [comment]
Maybe <https://handlebars-archive.knappi.org/>?

**Comment by jaylinski** [comment]
@Tejas-Ladhani This information is outdated. While transitioning to the new site, there was another domain-name used (ce76dc0f18c8b30143a47366c36d57387643f7c8). Now the "new" site has the same domain as the "old" site.

**Comment by Tejas-Ladhani** [comment]
@jaylinski, so all of the content has already been transferred to this "new" site. Is that correct?

**Comment by jaylinski** [comment]
I believe so, yes. (It was done by @nknapp)

**Comment by Tejas-Ladhani** [comment]
Okay, @jaylinski, let me correct the README file.

**Comment by jaylinski** [comment]
@Tejas-Ladhani yes please. PRs are welcome (to `master`-branch please).

**Comment by nknapp** [comment]
This paragraph should be removed, yes

**Comment by nknapp** [comment]
I removed it
