### ISSUE TITLE
Usage snippet in installation/precompilation is broken

### ISSUE THREAD

**Issue by scriptype** [handlebars-lang/docs#124]
The snippet is empty as can be seen here (https://handlebarsjs.com/installation/precompilation.html#usage):
<img width="802" alt="image" src="https://github.com/handlebars-lang/docs/assets/5516876/bc4190dd-9b5e-4234-bba8-d9a5ef0ed690">

I did some tracing and found the corresponding part in the md:

https://github.com/handlebars-lang/docs/blob/2178bc5de5e0208c84ca01c126865d458708aa1f/src/installation/precompilation.md?plain=1#L47

Which seems to be a custom syntax extension to VuePress' markdown, handled by this plugin here:

https://github.com/handlebars-lang/docs/blob/2178bc5de5e0208c84ca01c126865d458708aa1f/src/.vuepress/plugins/update-handlebars-cli-help.js#L5

But the above part seems to be authored quite some time ago. So, I suspect that one or more of these things might have changed since https://github.com/handlebars-lang/docs/commit/30f68847d88ea0c7f01995565ea3684da47aea01 and gone unnoticed:

- The way md syntax extensions should be written
- Path of the handlebars bin
- The way handlebars bin should be run
- The output when handlebars bin is run

Or maybe something else. But I'm not familiar with VuePress or tapping into md parsers, so I just wanted to report the issue and my contemplation on it ¯\\_(ツ)_/¯ Hope this helps!

**Comment by scriptype** [comment]
It looks like this is caused by using the `stderr` instead of `stdout` when the handlebars bin is run:

https://github.com/handlebars-lang/docs/blob/2178bc5de5e0208c84ca01c126865d458708aa1f/src/.vuepress/plugins/update-handlebars-cli-help.js#L39

`stderr` is empty, so an empty string is printed.

**Comment by jaylinski** [comment]
Thanks for the debugging, I opened a PR to fix the issue.
