### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by jonschlinkert** [handlebars-lang/docs#2]
I noticed that there is a `bot` repo here on the handlebars-lang org. 

Assuming the intent was to add a bot for helping with issues, etc. Is there a bot already set up somewhere or does anyone have a preference regarding the bot we use? @doowb and I created a bot system that we use with a lot of our projects. It's been really helpful. 

We don't need to use that, but if no one has a preference we can hook that up here, along with custom template and messaging, etc.

**Comment by nknapp** [comment]
I thought that the bot is for generating the site with Travis. @mmun what is the HandleBot for?

What exactly to you mean "helping with issues"?

**Comment by jonschlinkert** [comment]
> What exactly to you mean "helping with issues"?

Sorry, to clarify, when I saw the bot repo I jumped to the conclusion that it was for "auto-responses" to issues, which is a common use case for bots, but probably not as common as CI stuff. We use bots to reply to new issues or prs with something like this:

```
@username Thanks for the issue! If you're reporting a bug, please be sure to include:

- The version of handlebars.js you are using.
- Your configuration (This can be in a gist)
- The command line output, if applicable. (screenshot or gist is fine)
- What you expected to happen instead.

If your issue is related to one of the following, please open an issue there:
- foo
- bar
- baz
....
```

On prs you can remind people to review the contributing guide, etc. 

The biggest benefit we've seen from using bots, is that issue/pr quality is vastly better than when a bot is not present (people often update their issues right away with additional detail), and they don't feel offended since it's a bot asking and they don't feel singled out.

**Comment by nknapp** [comment]
I would use the github-templates for that. If at all.
