### ISSUE TITLE
question: license, author, copyright info, etc.

### ISSUE THREAD

**Issue by jonschlinkert** [handlebars-lang/docs#3]
I just wanted to get some feedback on these things:

- [ ] license - same as current site, or different?
- [ ] copyright - same as current site, or different?
- [ ] creative commons - in addition to other applicable licenses, we usually like to add a [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/) license for documentation. Any objections to that?
- [ ] author(s) - I assume that myself and other contributors to the new documentation will be authors, but I also don't lose sleep over this and don't have any problem with differences of opinion on how this works. Any guidance is welcome.

(while/if I'm waiting for answers I'll just go ahead and push up what was generated by my scaffolding tool, then we can amend the information based on feedback to this issue)

cc @wycats @nknapp (not sure who else should be mentioned on this)

(edited to add `CC` checklist item)

**Comment by nknapp** [comment]
I think, if we start off without using the current site, we could put everything under CC BY 3.0 and the authors would be us.
If we use that content, we should take the license, copyright and authors from the current site.

**Comment by nknapp** [comment]
For now, I have copied some old content and also the license. With @wycats permission, I would like to change it to a CC  BY license.

There should be a credits sections for authors who don't object being mentioned.
