### ISSUE TITLE
Guide: Literal Segments - correction needed but not sure what to??

### ISSUE THREAD

**Issue by moloko** [handlebars-lang/docs#47]
In [Literal Segments](https://github.com/handlebars-lang/docs/blob/master/src/guide/expressions.md#literal-segments) it says:
> JavaScript-style strings, `"` and `'`, may also be used instead `[` pairs.

Not quite sure if this should be:
> JavaScript-style strings, `"` and `'`, may also be used _inside of_ `[` pairs.

or:
> JavaScript-style strings, `"` and `'`, may also be used _instead of_ `[` pairs.

I think it's the first one?

**Comment by nknapp** [comment]
It's both actually, but the focus of this sentence is that you can also do `{{test."literal segment"}} and {{test.'literal segment' }}

**Comment by nknapp** [comment]
So the docs are as intended

**Comment by moloko** [comment]
@nknapp it needs to be changed to read “be used instead *of*”

**Comment by nknapp** [comment]
oh, I see right, thanks.

**Comment by nknapp** [comment]
This still needs to be translated to Chinese

**Comment by nknapp** [comment]
@Afanyiyu could you have a look the change in https://github.com/handlebars-lang/docs/commit/af55ea2c801745a28f71661336b0888df88b726c needs a translation in Chinese?
