### ISSUE TITLE
push access

### ISSUE THREAD

**Issue by jonschlinkert** [handlebars-lang/docs#5]
It seems I can't push to this repository. It's probably related to third-party access settings on the org, if someone could look into it.

**Comment by nknapp** [comment]
Mhm, the admin-page tells me that you have admin access to this repository.

**Comment by jonschlinkert** [comment]
I'm getting a 403

**Comment by nknapp** [comment]
I've made you an org owner, could you try again?

**Comment by nknapp** [comment]
@mmun, @ErisDS, @wycats I should have probably asked before elevating @jonschlinkert to owner. But I wanted to know if it helps with him pushing. I hope that was OK.

**Comment by jonschlinkert** [comment]
thanks, I'm pretty sure [these restrictions](https://github.com/organizations/handlebars-lang/settings/oauth_application_policy) are related. but I won't change those (and I won't get offended if you revoke owner permissions. I get it)

**Comment by jonschlinkert** [comment]
sorry, forgot to mention that I did try again. no luck

**Comment by nknapp** [comment]
Are you using ssh or http?

**Comment by jonschlinkert** [comment]
pretty sure i just tried both, but let me try ssh again (I thought I toggled off ssh earlier, to try https, but maybe it was already off...?)

**Comment by jonschlinkert** [comment]
ok, I'll have to look into this more when I have some time.

**Comment by nknapp** [comment]
Could you create a personal repo in and I pull everything over?

**Comment by nknapp** [comment]
> I won't get offended if you revoke owner permissions. I get it

I revoked it for the time. Personally, I don't have a problem with making you owner though.

**Comment by jonschlinkert** [comment]
I'd rather just get this fixed. If we do that I still won't be able to push, and we'll be in a weird state. 

In the meantime, maybe you could [clarify this](https://github.com/handlebars-lang/docs/issues/4#issuecomment-302858596)?

**Comment by nknapp** [comment]
OK. I have to go offline now for a while... I'll check back tonight at latest (in about 9 hours?), when the kids are in back.

**Comment by jonschlinkert** [comment]
no worries, I have a lot going on over the next few days. I don't think there is any reason to rush, but if you need to get things implemented before I can get around to it, don't feel obligated to wait on me.

**Comment by nknapp** [comment]
I just tried with a new account `nknapp-test` and I got this:

```
Username for 'https://github.com': nknapp-test
Password for 'https://nknapp-test@github.com': 
remote: You must verify your email address.
remote: See https://github.com/settings/emails.
fatal: unable to access 'https://github.com/handlebars-lang/docs.git/': The requested URL returned error: 403
```

As soon as I verified my email-address, it worked...

**Comment by nknapp** [comment]
I'd like to have the scaffold to before doing anything, but I could also start with outlining a structure in pure markdown...

**Comment by mmun** [comment]
I've made a discord server you can join if you'd like to discuss things with higher bandwidth: https://discord.gg/sAdAc29

**Comment by nknapp** [comment]
I am closing this because I don't really know how to fix the access-rights problem.
