### ISSUE TITLE
Need doc for registered Helper that uses async call 

### ISSUE THREAD

**Issue by ilanl** [handlebars-lang/docs#54]
Hi,

I have a lookup table cached in Redis, [productId: string]: string 
An async service that returns the productName based on productId

The context passed to the template is like:
productIds: ["1", "2"]

Template looks like:
{{#array}}{{ translate productIds }}{{/array}}

Any solution with handlebars? (Async + Handlebars + Typescript)

**Comment by nknapp** [comment]
There is no official solution to do that with Handlebars. The official way is to resolve all async parts before starting to render the template.

However, I have written a wrapper library in the past, to achieve this goal: https://www.npmjs.com/package/promised-handlebars

Yes, the last publish was 4 years ago, but it should still work and I don't know about any security issues. But the implementation is rather hacky in the sense that it does not use official APIs of the Handlebars core. Just have a look.
