### ISSUE TITLE
Technical writer wanted?

### ISSUE THREAD

**Issue by nknapp** [handlebars-lang/docs#6]
I thought, maybe in the long run we might need someone who has experience writing technical documentation. I am a software engineer, not a writer, although I like to write. But I think some of the things I write might be hard to understand. Even for the structure of the site, some opinions might be helpful.

If anybody knows somebody, that would be great.

**Comment by austinare** [comment]
I am a chemical engineering student looking to get into technical writing.  If you think I could help you with limited experience (writing school reports, research proposals, etc.) let me know.  I've done quite a bit of coding in python and I can deal with complicated concepts.

Also, I'm new to github so if this is totally out of character for a user i'm sorry.

**Comment by nknapp** [comment]
Thanks for your offer. If you really want to help out, that's great. Since you are new to Github, I'd like to point out that this is not a paid job opening. If you are looking  for a way to improve your writing skills, that's fine. But this an non-funded open-source project and **there is no money involved**.

The other thing is that I don't get money for it either, so my time is very limited. That means that if you want to work on this project, I would expect you to be pro-active. I can answer questions but I don't have a plan that says what to do next. The good thing is that there is no money involved, so there is no deadline either.

In case you are still interested: I don't know much about you apart from what you have written. This project is about technical documentation of an open source library, so it might be different than what you have done so far. You are the only one who can assess your usefulness.

* The draft of the new site is at: https://handlebars-lang.github.io/docs
* The old site is at http://handlebarsjs.com/

From a technical writer, I would hope for 

* Improvements to the documentation structure
* Feedback about parts that are difficult to understand and suggestions on how to improve them.
* Corrections of linguistical, grammatical and spelling errors

**Comment by austinare** [comment]
I think we are on the same page.  My time spent working on this will also be limited, but I will do my best to see where I can chip in.  

If I cannot understand the material or I don't have the time to make this work I will let you know.
