### ISSUE TITLE
algolia search

### ISSUE THREAD

**Issue by nknapp** [handlebars-lang/docs#8]

**Comment by ErisDS** [comment]
FYI I have experience with both algolia docsearch and algolia custom implementations. I can't offer much time to this project although I wholeheartedly support it, but maybe I can help with this 😄

**Comment by nknapp** [comment]
Thanks. There is an algolia search integrated  into the vuepress default theme.
It just needs to be configured. The only thing I'm not sure about is whether and how it is possible to get an open source team plan. I have created a personal account there, but this does not seem to be the right way.

**Comment by nknapp** [comment]
#46 added algolia search
