### ISSUE TITLE
Supporting `@last` for object iteration

### ISSUE THREAD

**Issue by yoshigev** [handlebars-lang/docs#82]
Hi,

The doc of built-in `#each` has the following assertion:

> When iterating over an object only the `@first` is available.

I believe that this assertion is not true since 2014 ([this commit](https://github.com/handlebars-lang/handlebars.js/commit/3a9440f954092558275cd4c05a35ba34bcbfa210)).

It is true that some implementation have not implemented this by default (see [my ticket](https://github.com/Handlebars-Net/Handlebars.Net/issues/480) for .NET), but please consider updating the assertion.

Thanks,
Yehoshua

**Comment by jaylinski** [comment]
@yoshigev Thanks for the info. I create a PR, can you have a look at it? #83
